config/routes.rb
Rails.application.routes.draw do
  resources :pets
  
  get "/signup" => "users#new"
  post "/users" => "users#create"

  get "/login" => "sessions#new"
  post "/sessions" => "sessions#create"
  get "/logout" => "sessions#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pet.rb
class Pet < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
 
  def authenticate_user
    redirect_to '/login', status: :see_other unless current_user
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  def index
    @pets = Pet.all
    render template: "pets/index"
  end
  
  def show
    @pet = Pet.find_by(id: params[:id])
    render template: "pets/show"
  end

  def new
    @pets = Pet.new
    render template: "pets/new"
  end

  def create
    @pet = Pet.new(
      name: params[:pet][:name],
      breed: params[:pet][:breed],
      image: params[:pet][:image]
    )
    @pet.save
    redirect_to "/pets"
  end

  def edit
    @pet = Pet.find_by(id: params[:id])
    render template: "pets/edit"
  end

  def update
    @pet = Pet.find_by(id: params[:id])
    @pet.name = params[:pet][:name]
    @pet.breed = params[:pet][:breed]
    @pet.image = params[:pet][:image]
    @pet.save
    redirect_to "/pets"
  end
  
  def destroy
    @pet = Pet.find_by(id: params[:id])
    @pet.destroy
    redirect_to "/pets", status: :see_other
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render template: "sessions/new"
  end
 
  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to "/"
    else
      redirect_to "/login"
    end
  end
 
  def destroy
    session[:user_id] = nil
    redirect_to "/login"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render template: "users/new"
  end

  def create
    @user = User.new(
      name: params[:user][:name],
      email: params[:user][:email],
      password: params[:user][:password],
      password_confirmation: params[:user][:password_confirmation],
    )
    if @user.save
      session[:user_id] = @user.id
      redirect_to "/"
    else
      render :new, status: :unprocessable_entity
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trackpets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pets/edit.html.erb
<h1>Edit Pet</h1>
<%= form_with model: @pet do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :breed %>
    <%= form.text_field :breed %>
  </div>
  <div>
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end%>

app/views/pets/index.html.erb
<h1>All Pets</h1>
<% @pets.each do |pet|%>
  <p>Name:<%=pet.name%></p>
  <p>Breed:<%=pet.breed%></p>
  <p>Image:<%= image_tag("#{pet.image}", size: "100")%></p>
  <a href="/pets/<%= pet.id %>">More info</a>
<%end%>


 <p><%= link_to "New pet", new_pet_path %></p>

app/views/pets/new.html.erb
<h1>Add Pet</h1>
<form method="post" action="/pets">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <div>
    <label>Name </label>
    <input type="text" name="pet[name]">
  </div>
  <div>
    <label>Breed </label>
    <input type="text" name="pet[breed]">
  </div>
  <div>
    <label>Image </label>
    <input type="text" name="pet[image]">
  </div>
  <div>
    <input type="submit" value="Create pet">
  </div>
</form>

app/views/pets/show.html.erb
<h1>Pet info</h1>
<h2>Name: <%= @pet.name %></h2>
<p>Breed: <%= @pet.breed %></p>
<p>Image: <%= @pet.image %></p>
<p><%= link_to "Edit pet", edit_pet_path(@pet) %></p>
<p><%= link_to "Destroy pet", pet_path(@pet), data: {turbo_method: :delete} %></p>

<a href="/pets">Back to all pets</a>

app/views/users/new.html.erb
<h1>Signup</h1>
<%= form_with model: @user do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
    <% @user.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
    <% @user.errors.full_messages_for(:email).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
    <% @user.errors.full_messages_for(:password).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
    <% @user.errors.full_messages_for(:password_confirmation).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>